services:

  logos-blockchain-node-0:
    image: ghcr.io/bacv/nomos-node:da7bd37-lssa
    ports:
      - "${PORT:-18080}:18080/tcp"
    volumes:
      - ./scripts:/etc/logos-blockchain/scripts
      - ./kzgrs_test_params:/kzgrs_test_params:z
      - ./node-config.yaml:/etc/logos-blockchain/node-config.yaml:z
      - ./deployment-settings.yaml:/etc/logos-blockchain/deployment-settings.yaml:z
    entrypoint: /etc/logos-blockchain/scripts/run_logos_blockchain_node.sh
