[package]
name = "lee"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
lee_core = { workspace = true, features = ["host"] }
program_loader_core.workspace = true

anyhow.workspace = true
thiserror.workspace = true
risc0-zkvm = { workspace = true, features = ["client"] }
serde_with.workspace = true
sha2.workspace = true
rand.workspace = true
borsh.workspace = true
hex.workspace = true
k256.workspace = true
risc0-binfmt = "3.0.2"
semver = { version = "1", optional = true }
log.workspace = true

[build-dependencies]
build_utils.workspace = true

[dev-dependencies]
lee_core = { workspace = true, features = ["test_utils"] }
test_methods = { path = "test_methods" }

hex-literal = "1.0.0"
test-case = "3.3.1"

[features]
default = []
prove = ["risc0-zkvm/prove", "dep:semver"]
test-utils = []
