# All-in-one docker compose configuration.
# It runs all services from this repo and the bedrock nodes in a single docker network.
# This is useful for development and testing purposes.

include:
  - path:
      bedrock/docker-compose.yml
  - path:
      lez/sequencer/service/docker-compose.devnet.yml
  - path:
      lez/indexer/service/docker-compose.yml
  - path:
      lez/explorer_service/docker-compose.yml
  - path:
      monitoring/docker-compose.yml
