[package]
name = "privacy_preserving_circuit_program"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

# Renaming binary to privacy_preserving_circuit for better looking.
[[bin]]
name = "privacy_preserving_circuit"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
borsh.workspace = true
lee_core.workspace = true
risc0-zkvm.workspace = true

[dev-dependencies]
lee_core = { workspace = true, features = ["host"] }
