[package]
name = "testnet_initial_state"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
key_protocol.workspace = true
lee.workspace = true
lee_core.workspace = true
system_accounts.workspace = true
programs.workspace = true

serde.workspace = true

[dev-dependencies]
fee_core.workspace = true

[lints]
workspace = true
