[package]
name = "chain_state"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
common.workspace = true
fee_core.workspace = true
lee.workspace = true
lee_core = { workspace = true, features = ["host"] }
system_accounts.workspace = true
logos-blockchain-core.workspace = true
logos-blockchain-zone-sdk.workspace = true

anyhow.workspace = true
borsh.workspace = true
futures.workspace = true
log.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
testnet_initial_state.workspace = true
serde_json.workspace = true
