[package]
name = "indexer_core"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[features]
default = []

[dependencies]
chain_state.workspace = true
common.workspace = true
logos-blockchain-zone-sdk.workspace = true
lee.workspace = true
lee_core = { workspace = true, features = ["host"] }
cross_zone.workspace = true
cross_zone_inbox_core.workspace = true
programs.workspace = true
storage.workspace = true
testnet_initial_state.workspace = true

anyhow.workspace = true
serde_with.workspace = true
arc-swap.workspace = true
log.workspace = true
serde.workspace = true
humantime-serde.workspace = true
borsh.workspace = true
futures.workspace = true
url.workspace = true
logos-blockchain-core.workspace = true
serde_json.workspace = true
async-stream.workspace = true
tokio.workspace = true
hex.workspace = true
thiserror.workspace = true

[dev-dependencies]
cross_zone = { workspace = true, features = ["test-utils"] }
tempfile.workspace = true
ping_core.workspace = true
test_methods.workspace = true
bridge_core.workspace = true
program_loader_core.workspace = true
