[package]
name = "test_program_guests"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
borsh.workspace = true
lee_core.workspace = true
authenticated_transfer_core.workspace = true
clock_core.workspace = true
faucet_core.workspace = true

risc0-zkvm.workspace = true

[package.metadata.cargo-machete]
ignored = ["risc0-zkvm"]
