[package]
edition = "2024"
license = { workspace = true }
name = "indexer_ffi"
version = "0.1.0"

[dependencies]
lee.workspace = true
indexer_core.workspace = true
indexer_service_protocol = { workspace = true, features = ["convert"] }

env_logger.workspace = true
log = { workspace = true }
tokio = { features = ["rt-multi-thread"], workspace = true }
futures.workspace = true
serde_json.workspace = true

[build-dependencies]
cbindgen = "0.29"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
name = "indexer_ffi"

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [
  "cbindgen",
] # machete does not recognize this for build dep and complains.
