[package]
name = "bridge_lock_program"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
authenticated_transfer_core = { workspace = true, features = ["image_id"] }
borsh.workspace = true
lee_core.workspace = true
bridge_lock_core.workspace = true
cross_zone_outbox_core.workspace = true
wrapped_token_core.workspace = true
risc0-zkvm.workspace = true

[package.metadata.cargo-machete]
ignored = ["risc0-zkvm"]
