[package]
name = "common"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
lee.workspace = true
lee_core = { workspace = true, features = ["host"] }
authenticated_transfer_core.workspace = true
clock_core.workspace = true
fee_core.workspace = true
bridge_core.workspace = true
bridge_lock_core.workspace = true
cross_zone_inbox_core.workspace = true
ping_core.workspace = true
programs.workspace = true
system_accounts.workspace = true

anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_with.workspace = true
base64.workspace = true
sha2.workspace = true
log.workspace = true
hex.workspace = true
borsh.workspace = true
logos-blockchain-common-http-client.workspace = true

[dev-dependencies]
lee = { workspace = true, features = ["test-utils"] }
