[package]
name = "programs"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[[bin]]
name = "amm"
path = "amm/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "associated_token_account"
path = "associated_token_account/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "bridge"
path = "bridge/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "clock"
path = "clock/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "faucet"
path = "faucet/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "fee"
path = "fee/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "token"
path = "token/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "cross_zone_outbox"
path = "cross_zone_outbox/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "cross_zone_inbox"
path = "cross_zone_inbox/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "ping_sender"
path = "ping_sender/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "ping_receiver"
path = "ping_receiver/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "bridge_lock"
path = "bridge_lock/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "wrapped_token"
path = "wrapped_token/src/main.rs"
required-features = ["programs"]

[[bin]]
name = "sequencer_stake"
path = "sequencer_stake/src/main.rs"
required-features = ["programs"]

[features]
# TODO: Uncomment once https://github.com/risc0/risc0/issues/3772 is resolved.
# default = ["artifacts"]

# This feature is only usable for library target.
# Activating this will cause library to include built binary artifacts and pack them into `Program` structs.
artifacts = ["dep:build_utils", "dep:lee"]

# Import dependencies required for program binaries.
# You don't need this if you only want to use the library target.
programs = [
  "dep:lee_core",
  "dep:amm_program",
  "dep:associated_token_account_program",
  "dep:token_program",
  "dep:amm_core",
  "dep:associated_token_account_core",
  "dep:authenticated_transfer_core",
  "dep:bridge_core",
  "dep:clock_core",
  "dep:faucet_core",
  "dep:fee_core",
  "dep:token_core",
  "dep:cross_zone_inbox_core",
  "dep:cross_zone_marker_core",
  "dep:cross_zone_outbox_core",
  "dep:bridge_lock_core",
  "dep:wrapped_token_core",
  "dep:ping_core",
  "dep:sequencer_stake_core",
]

[dependencies]
borsh.workspace = true
lee = { workspace = true, optional = true }
lee_core = { workspace = true, optional = true }
amm_core = { workspace = true, optional = true }
associated_token_account_core = { workspace = true, optional = true }
authenticated_transfer_core = { workspace = true, optional = true, features = [
  "image_id",
] }
bridge_core = { workspace = true, optional = true }
clock_core = { workspace = true, optional = true }
faucet_core = { workspace = true, optional = true }
fee_core = { workspace = true, optional = true }
token_core = { workspace = true, optional = true }
cross_zone_inbox_core = { workspace = true, optional = true }
cross_zone_marker_core = { workspace = true, optional = true }
cross_zone_outbox_core = { workspace = true, optional = true }
bridge_lock_core = { workspace = true, optional = true }
wrapped_token_core = { workspace = true, optional = true }
ping_core = { workspace = true, optional = true }
sequencer_stake_core = { workspace = true, optional = true }

amm_program = { path = "amm", optional = true }
associated_token_account_program = { path = "associated_token_account", optional = true }
token_program = { path = "token", optional = true }

[build-dependencies]
build_utils = { workspace = true, optional = true }

[dev-dependencies]
bridge_core = { workspace = true }
