[package]
name = "test_fixtures"
version = "0.1.0"
edition = "2024"
license = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
common.workspace = true
indexer_service.workspace = true
key_protocol.workspace = true
lee.workspace = true
lee_core = { workspace = true, features = ["host"] }
sequencer_core.workspace = true
sequencer_service.workspace = true
sequencer_stake_core.workspace = true
sequencer_service_rpc = { workspace = true, features = ["client"] }
sequencer_storage_actor.workspace = true
wallet.workspace = true
programs.workspace = true

anyhow.workspace = true
bip39.workspace = true
bytesize.workspace = true
env_logger.workspace = true
futures.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["ws-client"] }
kameo.workspace = true
log.workspace = true
num-bigint.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
testcontainers = { version = "0.27.3", features = ["docker-compose"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tokio-util.workspace = true
url.workspace = true
time.workspace = true

logos-blockchain-key-management-system-service.workspace = true
