[package]
name = "sequencer_service_protocol"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[dependencies]
common.workspace = true
lee.workspace = true
lee_core.workspace = true

hex.workspace = true
serde.workspace = true
serde_with.workspace = true

[dev-dependencies]
serde_json.workspace = true
