[package]
name = "key_protocol"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[features]
default = []
test_utils = []

[dependencies]
lee.workspace = true
lee_core.workspace = true
common.workspace = true

anyhow.workspace = true
serde.workspace = true
k256.workspace = true
ml-kem.workspace = true
sha2.workspace = true
rand.workspace = true
hex.workspace = true
aes-gcm.workspace = true
bip39.workspace = true
hmac-sha512.workspace = true
thiserror.workspace = true
itertools.workspace = true

[dev-dependencies]
lee_core = { workspace = true, features = ["test_utils"] }
base58.workspace = true
bincode.workspace = true
