[package]
name = "authenticated_transfer_core"
version = "0.1.0"
edition = "2024"
license = { workspace = true }

[lints]
workspace = true

[features]
image_id = ["dep:build_utils"]

[dependencies]
borsh.workspace = true
lee_core.workspace = true

[build-dependencies]
build_utils = { workspace = true, optional = true }
