use std::{future::Future, net::SocketAddr, path::Path};

use anyhow::{Context as _, Result};
use futures::never::Never;
use kameo::actor::{ActorRef, Recipient, Spawn as _};
use kameo_actors::scheduler::{Scheduler, SetInterval};
use log::info;
pub use sequencer_core::config::*;
use sequencer_core::load_or_create_signing_key;
use sequencer_executor_actor::ExecutorActor;
use sequencer_gossip_actor::{GossipActor, protocol::PublishTransaction};
use sequencer_rpc_server_actor::RpcServerActor;
use sequencer_storage_actor::StorageActor;
use tokio::select;

use crate::actor_handle::ActorHandle;

mod actor_handle;

#[cfg(not(feature = "standalone"))]
type BlockPublisher = sequencer_core::block_publisher::ZoneSdkPublisher;

#[cfg(feature = "standalone")]
type BlockPublisher = sequencer_core::mock::MockBlockPublisher;

/// Handle to manage the sequencer and its tasks.
///
/// Implements `Drop` to ensure all actors are killed when dropped.
pub struct SequencerHandle {
    // NOTE: Order of fields matters as it affects drop order.
    scheduler: ActorHandle<Scheduler>,
    rpc_server: ActorHandle<RpcServerActor>,
    /// `None` when gossip is unconfigured.
    gossip: Option<Gossip>,
    executor: ActorHandle<ExecutorActor<StorageActor, BlockPublisher>>,
    storage: ActorHandle<StorageActor>,
    addr: SocketAddr,
}

/// The gossip actor and its companions.
struct Gossip {
    actor: ActorHandle<sequencer_gossip_actor::GossipActor>,
    bootstrap_addrs: Vec<sequencer_gossip_actor::Multiaddr>,
    /// Aborts the gossip outage warner when the handle is dropped.
    _watchdog: sequencer_gossip_actor::WatchdogGuard,
}

impl SequencerHandle {
    const fn new(
        scheduler: ActorHandle<Scheduler>,
        rpc_server: ActorHandle<RpcServerActor>,
        gossip: Option<Gossip>,
        executor: ActorHandle<ExecutorActor<StorageActor, BlockPublisher>>,
        storage: ActorHandle<StorageActor>,
        addr: SocketAddr,
    ) -> Self {
        Self {
            scheduler,
            rpc_server,
            gossip,
            executor,
            storage,
            addr,
        }
    }

    /// Stops the sequencer and waits for every part of it to be gone.
    /// executor itself.
    pub async fn shutdown(self) {
        let Self {
            scheduler,
            rpc_server,
            gossip,
            executor,
            storage,
            addr: _,
        } = self;

        // NOTE: Order of shutdown matters. Make sure it follows the order of fields in the struct.
        scheduler.shutdown().await;
        rpc_server.shutdown().await;
        if let Some(gossip) = gossip {
            gossip.actor.shutdown().await;
        }
        executor.shutdown().await;
        storage.shutdown().await;
    }

    /// Wait for any of the sequencer tasks to fail and return the error.
    ///
    /// Gossip is deliberately not watched here: if it goes down the node
    /// continues to operate in L1-only mode; the gossip outage watchdog
    /// warns operators instead.
    #[expect(
        clippy::integer_division_remainder_used,
        reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
    )]
    pub async fn failed(&self) -> Result<Never> {
        let Self {
            executor,
            rpc_server,
            scheduler,
            storage,
            addr: _,
            gossip: _,
        } = self;

        select! {
            Err(err) = executor.failed() => {
                Err(err)
            }
            Err(err) = rpc_server.failed() => {
                Err(err)
            }
            Err(err) = scheduler.failed() => {
                Err(err)
            }
            Err(err) = storage.failed() => {
                Err(err)
            }
        }
    }

    /// Check if all Sequencer tasks are still running.
    ///
    /// Return `false` if any of the tasks has failed and `true` otherwise.
    /// Error of the failed task can be retrieved by awaiting on [`Self::failed()`].
    ///
    /// Gossip is not part of this: if it goes down the node continues to operate
    /// in L1-only mode.
    #[must_use]
    pub fn is_healthy(&self) -> bool {
        let Self {
            executor,
            rpc_server,
            scheduler,
            storage,
            addr: _,
            gossip: _,
        } = self;

        executor.is_healthy()
            && rpc_server.is_healthy()
            && scheduler.is_healthy()
            && storage.is_healthy()
    }

    #[must_use]
    pub const fn addr(&self) -> SocketAddr {
        self.addr
    }

    /// Multiaddrs (with the `/p2p/` peer id suffix) other nodes can use as
    /// gossip `bootstrap_peers`. `None` when gossip is unconfigured.
    #[must_use]
    pub fn gossip_bootstrap_addrs(&self) -> Option<Vec<sequencer_gossip_actor::Multiaddr>> {
        self.gossip
            .as_ref()
            .map(|gossip| gossip.bootstrap_addrs.clone())
    }
}

#[expect(
    clippy::manual_async_fn,
    reason = "Explicit Send future works around rust-lang/rust#100013"
)]
pub fn run(
    config: SequencerConfig,
    listen_addr: SocketAddr,
) -> impl Future<Output = Result<SequencerHandle>> + Send + 'static {
    async move {
        let block_timeout = config.block_create_timeout;
        let max_block_size = config.max_block_size;

        let gossip_config = config.gossip.clone();
        let bedrock_config = config.bedrock_config.clone();
        let sequencer_home = config.home.clone();

        let storage =
            StorageActor::new(&config.db_path()).context("Failed to initialize Storage Actor")?;
        let storage_ref = StorageActor::spawn(storage);
        info!("Storage Actor spawned");

        let executor = ExecutorActor::new(config, storage_ref.clone()).await;
        let executor_ref = ExecutorActor::spawn(executor);
        info!("Executor Actor spawned");

        let scheduler_ref = Scheduler::spawn(Scheduler::new());

        let (gossip, gossip_publisher) = match gossip_config {
            None => None,
            Some(gossip_config) => Some(
                setup_gossip(
                    gossip_config,
                    *bedrock_config.channel_id.as_ref(),
                    &sequencer_home,
                    max_block_size.as_u64(),
                    &executor_ref,
                    &scheduler_ref,
                )
                .await?,
            ),
        }
        .unzip();

        let rpc_server = RpcServerActor::new(
            listen_addr,
            max_block_size,
            executor_ref.clone(),
            gossip_publisher,
        )
        .await
        .context("Failed to initialize RPC Server Actor")?;
        let addr = rpc_server.addr();
        let rpc_server_ref = RpcServerActor::spawn(rpc_server);
        info!("RPC Server Actor spawned");

        scheduler_ref
            .tell(
                SetInterval::new(
                    executor_ref.downgrade(),
                    block_timeout,
                    sequencer_executor_actor::protocol::ProduceBlock,
                )
                .start_delay(block_timeout)
                .set_missed_tick_behaviour(tokio::time::MissedTickBehavior::Delay),
            )
            .await?;
        info!("Block production scheduler started");

        Ok(SequencerHandle::new(
            ActorHandle::new(scheduler_ref),
            ActorHandle::new(rpc_server_ref),
            gossip,
            ActorHandle::new(executor_ref),
            ActorHandle::new(storage_ref),
            addr,
        ))
    }
}

/// Starts the gossip actor together with its outage watchdog and its
/// scheduled bootstrap retries, returning its service handle and the
/// recipient the RPC server publishes admitted transactions to.
async fn setup_gossip(
    gossip_config: GossipConfig,
    channel_id: [u8; 32],
    sequencer_home: &Path,
    max_block_size: u64,
    executor_ref: &ActorRef<ExecutorActor<StorageActor, BlockPublisher>>,
    scheduler_ref: &ActorRef<Scheduler>,
) -> Result<(Gossip, Recipient<PublishTransaction>)> {
    // The node's L1 bedrock signing key is deliberately reused as the
    // libp2p identity; `GossipActor::new` derives the keypair.
    let signing_key = load_or_create_signing_key(&sequencer_home.join("bedrock_signing_key"))?;
    // Gossiped transactions enter through the executor's admission door
    // (fee screen + mempool push), same as RPC submissions — gossip never
    // touches the mempool directly.
    let submit_ref = executor_ref.clone();
    let submit: sequencer_gossip_actor::IngestSubmit = std::sync::Arc::new(move |transaction| {
        let executor_submit_ref = submit_ref.clone();
        Box::pin(async move {
            use sequencer_executor_actor::protocol::{Transaction, TransactionOrigin};
            let message = Transaction {
                transaction,
                origin: TransactionOrigin::Gossip,
            };
            executor_submit_ref.ask(message).await.map_err(Into::into)
        })
    });

    let gossip_actor = GossipActor::new(
        gossip_config,
        channel_id,
        signing_key,
        max_block_size,
        submit,
    )
    .await
    .context("Failed to start sequencer gossip network")?;
    info!("Gossip network started as {}", gossip_actor.local_peer_id());
    let bootstrap_addrs = gossip_actor.bootstrap_addrs();

    let gossip_ref = GossipActor::spawn_with_mailbox(
        gossip_actor,
        kameo::mailbox::bounded(sequencer_gossip_actor::MAILBOX_CAPACITY),
    );
    info!("Gossip Actor spawned");
    let watchdog = sequencer_gossip_actor::spawn_gossip_outage_watchdog(gossip_ref.clone());

    // Startup already dialed the bootstrap peers, so the first retry waits
    // a full interval.
    scheduler_ref
        .tell(
            SetInterval::new(
                gossip_ref.downgrade(),
                sequencer_gossip_actor::BOOTSTRAP_RETRY_INTERVAL,
                sequencer_gossip_actor::protocol::RetryBootstrap,
            )
            .start_delay(sequencer_gossip_actor::BOOTSTRAP_RETRY_INTERVAL),
        )
        .await?;

    let publisher = gossip_ref.clone().recipient();
    Ok((
        Gossip {
            actor: ActorHandle::new(gossip_ref),
            bootstrap_addrs,
            _watchdog: watchdog,
        },
        publisher,
    ))
}
