use std::{future::Future, net::SocketAddr};

use anyhow::{Context as _, Result};
use futures::never::Never;
use kameo::actor::Spawn as _;
use kameo_actors::scheduler::{Scheduler, SetInterval};
use log::info;
pub use sequencer_core::config::*;
use sequencer_core::load_or_create_signing_key;
use sequencer_executor_actor::ExecutorActor;
use sequencer_rpc_server_actor::RpcServerActor;
use sequencer_storage_actor::StorageActor;
use tokio::select;

use crate::actor_handle::ActorHandle;

mod actor_handle;

#[cfg(not(feature = "standalone"))]
type BlockPublisher = sequencer_core::block_publisher::ZoneSdkPublisher;

#[cfg(feature = "standalone")]
type BlockPublisher = sequencer_core::mock::MockBlockPublisher;

/// Handle to manage the sequencer and its tasks.
///
/// Implements `Drop` to ensure all actors are killed when dropped.
pub struct SequencerHandle {
    // NOTE: Order of fields matters as it affects drop order.
    scheduler: ActorHandle<Scheduler>,
    rpc_server: ActorHandle<RpcServerActor>,
    executor: ActorHandle<ExecutorActor<StorageActor, BlockPublisher>>,
    storage: ActorHandle<StorageActor>,
    addr: SocketAddr,
    /// Deliberately NOT part of [`Self::failed`]/[`Self::is_healthy`]: gossip
    /// going down degrades the node to L1-only, it never halts it (the
    /// watchdog warns operators instead). `None` when gossip is unconfigured.
    gossip: Option<ActorHandle<sequencer_gossip_actor::GossipActor>>,
    gossip_bootstrap_addrs: Option<Vec<sequencer_gossip_actor::Multiaddr>>,
    /// Aborts the L1-only outage warner when the handle is dropped.
    gossip_watchdog: Option<sequencer_gossip_actor::WatchdogGuard>,
}

impl SequencerHandle {
    const fn new(
        scheduler: ActorHandle<Scheduler>,
        rpc_server: ActorHandle<RpcServerActor>,
        gossip: Option<ActorHandle<sequencer_gossip_actor::GossipActor>>,
        executor: ActorHandle<ExecutorActor<StorageActor, BlockPublisher>>,
        storage: ActorHandle<StorageActor>,
        addr: SocketAddr,
        gossip_bootstrap_addrs: Option<Vec<sequencer_gossip_actor::Multiaddr>>,
        gossip_watchdog: Option<sequencer_gossip_actor::WatchdogGuard>,
    ) -> Self {
        Self {
            scheduler,
            rpc_server,
            executor,
            storage,
            addr,
            gossip,
            gossip_bootstrap_addrs,
            gossip_watchdog,
        }
    }

    /// Stops the sequencer and waits for every part of it to be gone.
    /// executor itself.
    pub async fn shutdown(self) {
        let Self {
            scheduler,
            rpc_server,
            gossip,
            executor,
            storage,
            addr: _,
            gossip_bootstrap_addrs: _,
            gossip_watchdog: _,
        } = self;

        // NOTE: Order of shutdown matters. Make sure it follows the order of fields in the struct.
        scheduler.shutdown().await;
        rpc_server.shutdown().await;
        if let Some(gossip) = gossip {
            gossip.shutdown().await;
        }
        executor.shutdown().await;
        storage.shutdown().await;
    }

    /// Wait for any of the sequencer tasks to fail and return the error.
    #[expect(
        clippy::integer_division_remainder_used,
        reason = "Generated by select! macro, can't be easily rewritten to avoid this lint"
    )]
    pub async fn failed(&self) -> Result<Never> {
        let Self {
            executor,
            rpc_server,
            scheduler,
            storage,
            addr: _,
            // A gossip failure never halts the node; see the field docs.
            gossip: _,
            gossip_bootstrap_addrs: _,
            gossip_watchdog: _,
        } = self;

        select! {
            Err(err) = executor.failed() => {
                Err(err)
            }
            Err(err) = rpc_server.failed() => {
                Err(err)
            }
            Err(err) = scheduler.failed() => {
                Err(err)
            }
            Err(err) = storage.failed() => {
                Err(err)
            }
        }
    }

    /// Check if all Sequencer tasks are still running.
    ///
    /// Return `false` if any of the tasks has failed and `true` otherwise.
    /// Error of the failed task can be retrieved by awaiting on [`Self::failed()`].
    #[must_use]
    pub fn is_healthy(&self) -> bool {
        let Self {
            executor,
            rpc_server,
            scheduler,
            storage,
            addr: _,
            // A gossip failure never halts the node; see the field docs.
            gossip: _,
            gossip_bootstrap_addrs: _,
            gossip_watchdog: _,
        } = self;

        executor.is_healthy()
            && rpc_server.is_healthy()
            && scheduler.is_healthy()
            && storage.is_healthy()
    }

    #[must_use]
    pub const fn addr(&self) -> SocketAddr {
        self.addr
    }

    /// Multiaddrs (with the `/p2p/` peer id suffix) other nodes can use as
    /// gossip `bootstrap_peers`. `None` when gossip is unconfigured.
    #[must_use]
    pub fn gossip_bootstrap_addrs(&self) -> Option<Vec<sequencer_gossip_actor::Multiaddr>> {
        self.gossip_bootstrap_addrs.clone()
    }
}

#[expect(
    clippy::manual_async_fn,
    reason = "Explicit Send future works around rust-lang/rust#100013"
)]
pub fn run(
    config: SequencerConfig,
    listen_addr: SocketAddr,
) -> impl Future<Output = Result<SequencerHandle>> + Send + 'static {
    async move {
        let block_timeout = config.block_create_timeout;
        let max_block_size = config.max_block_size;

        let gossip_config = config.gossip.clone();
        let bedrock_config = config.bedrock_config.clone();
        let sequencer_home = config.home.clone();

        let storage =
            StorageActor::new(&config.db_path()).context("Failed to initialize Storage Actor")?;
        let storage_ref = StorageActor::spawn(storage);
        info!("Storage Actor spawned");

        let executor = ExecutorActor::new(config, storage_ref.clone()).await;
        let executor_ref = ExecutorActor::spawn(executor);
        info!("Executor Actor spawned");

        let (gossip, tx_publisher, gossip_bootstrap_addrs, gossip_watchdog) = match gossip_config {
            None => (None, None, None, None),
            Some(gossip_config) => {
                // The node's L1 bedrock signing key is deliberately reused as the
                // libp2p identity; `GossipActor::new` derives the keypair.
                let signing_key =
                    load_or_create_signing_key(&sequencer_home.join("bedrock_signing_key"))?;
                let channel_id = *bedrock_config.channel_id.as_ref();
                // Gossiped transactions enter through the executor's admission
                // door (fee screen + mempool push), same as RPC submissions —
                // gossip never touches the mempool directly.
                let submit_ref = executor_ref.clone();
                let submit: sequencer_gossip_actor::IngestSubmit =
                    std::sync::Arc::new(move |transaction| {
                        let executor_submit_ref = submit_ref.clone();
                        Box::pin(async move {
                            use sequencer_executor_actor::protocol::{
                                Transaction, TransactionOrigin,
                            };
                            let message = Transaction {
                                transaction,
                                origin: TransactionOrigin::Gossip,
                            };
                            executor_submit_ref.ask(message).await.map_err(Into::into)
                        })
                    });
                let gossip_actor = sequencer_gossip_actor::GossipActor::new(
                    gossip_config,
                    channel_id,
                    signing_key,
                    max_block_size.as_u64(),
                    submit,
                )
                .await
                .context("Failed to start sequencer gossip network")?;
                info!("Gossip network started as {}", gossip_actor.local_peer_id());
                let bootstrap_addrs = gossip_actor.bootstrap_addrs();
                let gossip_ref = sequencer_gossip_actor::GossipActor::spawn(gossip_actor);
                info!("Gossip Actor spawned");
                let watchdog = sequencer_gossip_actor::spawn_l1_only_watchdog(gossip_ref.clone());
                (
                    Some(ActorHandle::new(gossip_ref.clone())),
                    Some(sequencer_gossip_actor::GossipTxPublisher::new(gossip_ref)),
                    Some(bootstrap_addrs),
                    Some(watchdog),
                )
            }
        };

        let rpc_server = RpcServerActor::new(
            listen_addr,
            max_block_size,
            executor_ref.clone(),
            tx_publisher,
        )
        .await
        .context("Failed to initialize RPC Server Actor")?;
        let addr = rpc_server.addr();
        let rpc_server_ref = RpcServerActor::spawn(rpc_server);
        info!("RPC Server Actor spawned");

        let scheduler_ref = Scheduler::spawn(Scheduler::new());
        scheduler_ref
            .tell(
                SetInterval::new(
                    executor_ref.downgrade(),
                    block_timeout,
                    sequencer_executor_actor::protocol::ProduceBlock,
                )
                .start_delay(block_timeout)
                .set_missed_tick_behaviour(tokio::time::MissedTickBehavior::Delay),
            )
            .await?;
        info!("Block production scheduler started");

        Ok(SequencerHandle::new(
            ActorHandle::new(scheduler_ref),
            ActorHandle::new(rpc_server_ref),
            gossip,
            ActorHandle::new(executor_ref),
            ActorHandle::new(storage_ref),
            addr,
            gossip_bootstrap_addrs,
            gossip_watchdog,
        ))
    }
}
